"""empty message

Revision ID: 5a449891911e
Revises: a6802f7b054e
Create Date: 2025-12-31 20:53:33.062369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a449891911e'
down_revision = 'a6802f7b054e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('credit_unit',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('c_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('c_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('credit_unit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
