name: Deploy Ansible 

on: 
  push:
    branches: [ main ]


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Ansible repository
        uses: actions/checkout@v4
        with:
          repository: Basharr-py/Ansible-Config
          path: ansible-lab

      - name: Configure Github OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Check SSM
        run: aws ssm describe-instance-information

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirement.txt

      - name: Install Ansible
        run: pip install ansible

      - name: Install Ansible AWS collection
        run: ansible-galaxy collection install amazon.aws

      - name: Install Session Manager plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" \
            -o session-manager-plugin.deb
          sudo dpkg -i session-manager-plugin.deb

      - name: Test private servers
        working-directory: ansible-lab
        run: |
          ansible flask_private -i inventories/for_flask -m ping