name: Multi Job Test

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "This is job ONE" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: hello.txt

  second:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: Read file
        run: cat hello.txt